### ISSUE TITLE
Deprecated dependencies warnings (move to Smithy)

### ISSUE THREAD

**Issue by rogerweb** [awslabs/aws-sdk-v3-js-proxy#29]
Not a bug neither a feature request.

## Current Behavior

```bash
$ npm install aws-sdk-v3-proxy

npm WARN deprecated @aws-sdk/node-http-handler@3.374.0: This package has moved to @smithy/node-http-handler
npm WARN deprecated @aws-sdk/protocol-http@3.374.0: This package has moved to @smithy/protocol-http
```

## Expected Behavior

No warnings about deprecated packages.

## Steps to Reproduce the Problem

  1. npm install aws-sdk-v3-proxy
  2. Observe the warnings.

## Environment

- Version: 2.1.2
- Platform: Linux
- Node.js Version: v20.12.2

**Comment by ayalade** [comment]
is there any ETA for this fix?

**Comment by ryansonshine** [comment]
Thanks for the contribution @rogerweb . I've opened #30 to address this issue, but it will require someone from AWS to approve and merge since I no longer work there and don't have permissions.

**Comment by ryansonshine** [comment]
cc: @smguggen

**Comment by smguggen** [comment]
Will get on this today, thank you @ryansonshine and @rogerweb
